apiVersion: apps/v1
kind: Deployment
metadata:
  name:  springboot
  namespace: default
  labels:
    app:  springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  springboot
    spec:
      containers:
      - name:  springboot
        image:  277707131963.dkr.ecr.ap-south-1.amazonaws.com/springboot:${env.BUILD_NUMBER} #dockerhandson/spring-boot-mongo:1 #mohdkhalandar/spring-boot-mongo-docker:1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: MONGO_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: springbootconfig
              key: DB_HOST 
        - name:  MONGO_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name:  mongodbsecret
              key:  mongodb-username
        - name:  MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  mongodbsecret
              key:  mongodb-password 
        ports:
        - containerPort:  8080
          name:  webapp
---
kind: Service
apiVersion: v1
metadata:
  name:  springboot-service
spec:
  selector:
    app:  springboot
  type:  LoadBalancer
  ports:
  - port:  80
    targetPort:  8080
    nodePort: 30300
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbapp
  labels:
    app: mongodbapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodbapp
  template:
    metadata:
      labels:
        app: mongodbapp
    spec:
      containers:
      - name: mongodbapp
        image: mongo
        ports:
        - name: mongodb
          containerPort:  27017
          protocol: TCP
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodbsecret
              key: mongodb-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodbsecret
              key: mongodb-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  selector:
    app: mongodbapp
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
